name: Run Python Script

on: workflow_dispatch

# on:
#   schedule:
#     - cron: ' * * * * * '  # Schedule to run daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
            python-version: '3.9'
            cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt 
    - name: Debugging Output
      run: |
          ls -la
        
    - name: Read and Update Last Tweeted Index
      run: |
          # Read the index of the last tweeted tip
          last_tweeted_index_file="last_tweeted_tip.txt"
          last_tweeted_index=0
          if [ -f "$last_tweeted_index_file" ]; then
            last_tweeted_index=$(cat "$last_tweeted_index_file")
          fi

          # Debugging output
          echo "Last tweeted index: $last_tweeted_index"

          # Determine the index of the next tip to tweet
          next_tip_index=$((last_tweeted_index + 1))
          # if [ "$next_tip_index" -ge "${#tips[@]}" ]; then
          #   next_tip_index=0
          fi

          # Debugging output
          echo "Next tip index: $next_tip_index"

          # Store the index of the next tip to tweet
          echo "$next_tip_index" > "$last_tweeted_index_file"
    - name: Commit changes
      run: |
        git config --global user.email "triksters123@gmail.com"
        git config --global user.name "Rx-11"
        git pull
        git add last_tweeted_tip.txt
        git commit -m "Update last_tweeted_tip.txt"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

    - name: Run Python Script
      run: python twitter.py
