name: Post Millionaire Mindset Tips

on: workflow_dispatch

# on:
#   schedule:
#     - cron: '0 */4 * * *' # Run every 4 hours

jobs:
  post_tweets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Read Tips from JSON File
        run: |
          # Read the tips from the JSON file
          json_file="x.json"
          tips=($(jq -r '.millionaire_mindset_tips[]' "$json_file"))
          
          # Debugging output
          echo "Tips: ${tips[@]}"
        env:
          TZ: UTC
        working-directory: ${{ github.workspace }}

      - name: Read and Update Last Tweeted Index
        run: |
          # Read the index of the last tweeted tip
          last_tweeted_index_file="last_tweeted_tip.txt"
          last_tweeted_index=0
          if [ -f "$last_tweeted_index_file" ]; then
            last_tweeted_index=$(cat "$last_tweeted_index_file")
          fi

          # Debugging output
          echo "Last tweeted index: $last_tweeted_index"

          # Determine the index of the next tip to tweet
          next_tip_index=$((last_tweeted_index + 1))
          if [ "$next_tip_index" -ge "${#tips[@]}" ]; then
            next_tip_index=0
          fi

          # Debugging output
          echo "Next tip index: $next_tip_index"

          # Store the index of the next tip to tweet
          echo "$next_tip_index" > "$last_tweeted_index_file"
        working-directory: ${{ github.workspace }}

      - name: Post Tweet
        run: |
          # Your tweet posting code here
          # You can use "${tips[next_tip_index]}" to access the next tip.
          import tweepy

          # Set up your Twitter API credentials
          # (Insert your Twitter API credentials here)

          # Authenticate with Twitter
          # (Insert your authentication code here)
          client = tweepy.Client(
          consumer_key="pKP7JTSe41RMfBKcLaE2KCL9J",
          consumer_secret="SWkTaUaJSEVDjrPNzP6qVJkDNnv0BfBKJor92tZIRqhZ43XGUa",
          access_token= "1715849789957406720-sWSZpkpQX5L5InypYXA967HisBTq3S",
          access_token_secret="4Yu1nk6xetMkITbqwEVonVhdzax0n96HnoVkllNP0dKFm",
          )
          

          # Use the next tip based on the determined index
          tweet = tips[next_tip_index]

          try:
              client.create_tweet(text=tweet)
              echo "$next_tip_index" > "$last_tweeted_index_file"  # Update the last tweeted tip index
              print(f"Tweeted: {tweet}")
          except Exception as e:
              print(f"Error posting tweet: {e}")
        # env:
        #   TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        #   TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        #   TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        #   TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
